import type { components } from "../src/api.generated";

/**
 * Request-body types sourced directly from the committed OpenAPI contract
 * (`src/api.generated.ts`, generated by `npm run generate:types`). Using these
 * for outgoing payloads means the frontend tracks the backend's DTOs
 * automatically — a field rename on the server surfaces as a type error here
 * after the next `generate:types`, guarded by the contract test.
 *
 * Only DTOs the spec fully describes are re-exported. Some request DTOs still
 * serialise as empty in the spec (e.g. CreateClassFeeDto, UpdateProfileDto)
 * because they lack `@ApiProperty`/type annotations on the backend — adopting
 * those is a backend follow-up, tracked in Milestone 5.
 */
type Schemas = components["schemas"];

export type CreateReceiptUploadDto = Schemas["CreateReceiptUploadDto"];
export type CreateReceiptDownloadDto = Schemas["CreateReceiptDownloadDto"];
export type ReversePaymentDto = Schemas["ReversePaymentDto"];

// Enrollment invites — onboarding parents who paid the school before Lopay.
export type CreateEnrollmentInviteDto = Schemas["CreateEnrollmentInviteDto"];
export type ClaimEnrollmentInviteDto = Schemas["ClaimEnrollmentInviteDto"];
export type DisputeEnrollmentInviteDto = Schemas["DisputeEnrollmentInviteDto"];
export type RevokeEnrollmentInviteDto = Schemas["RevokeEnrollmentInviteDto"];
export type AmendMigratedPaymentDto = Schemas["AmendMigratedPaymentDto"];
